facturation_project/facturation/urls.py
# facturation:login/urls.py
from django.urls import path
from . import views

 
app_name= 'facturation'
urlpatterns = [
    #login paths
    path('register/', views.register_user, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    #homepage paths
    path('', views.homepage, name='homepage'),
    path('homepage/', views.homepage, name='homepage'),
    #sidebar paths

    path('factures',views.homepage,name='factures'),
    path('fournisseurs/',views.fournisseurs,name='fournisseurs'),
    path('services/', views.services, name='services'),
    #CRUD for Factures
    path('add_facture/', views.add_facture, name='add_facture'),
    path('facture/<int:pk>/', views.view_facture, name='view_facture'),
    path('facture/<int:pk>/update/', views.update_facture, name='update_facture'),
    path('facture/<int:pk>/delete/', views.delete_facture, name='delete_facture'),
    # CRUD for Fournisseurs
    path('fournisseur/add/', views.add_fournisseur, name='add_fournisseur'),
    path('fournisseur/<int:pk>/', views.view_fournisseur, name='view_fournisseur'),
    path('fournisseur/<int:pk>/update/', views.update_fournisseur, name='update_fournisseur'),
    path('fournisseur/<int:pk>/delete/', views.delete_fournisseur, name='delete_fournisseur'),
    # CRUD for Services
    path('service/add/', views.add_service, name='add_service'),
    path('service/<int:pk>/', views.view_service, name='view_service'),
    path('service/<int:pk>/update/', views.update_service, name='update_service'),
    path('service/<int:pk>/delete/', views.delete_service, name='delete_service'),
    #exporting_importing
    path('export/', views.export_data, name="export_data"),

]

facturation_project/facturation_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),


    path('', include('facturation.urls',namespace='facturation')),
         
]

facturation_project/templates/layouts/base-fullscreen.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gestion de Factures</title>
    
    <link rel="stylesheet" type="text/css" href="/static/assets/css/login.css">
    <!-- Add your CSS and other stylesheets here -->
    <style>
      /* ... your existing CSS ... */

      /* Center the sign-in section */
      .center-container {
          display: flex;
          justify-content: center;
          align-items: center;
          height: 100vh;
      }

      .login-card {
          background-color: #ffffff;
          padding: 20px;
          border: 1px solid #ccc;
          border-radius: 10px;
          box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
          width: 300px;
      }
  </style>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
       
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'facturation:login' %}">Se connecter</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'facturation:register' %}">S'inscrire</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="content">
      <div class="center-container">
        <div class="login-card">
            {% block content %}{% endblock %}
        </div>
      </div>
    </div>
        

    <footer class="footer">
        <div class="container text-center">
            
            <p class="title">Gestion des Factures</p>
            <p>© 2023 Abrar Invest</p>
        </div>
    </footer>

    <!-- Add your scripts here -->
</body>
</html>

facturation_project/templates/layouts/base.html
<!DOCTYPE html>
{% if user.is_authenticated %}
{% load group_tags %}
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gestion de Factures</title>
    <link rel="stylesheet" type="text/css" href="/static/assets/css/style.css">
    <link rel="stylesheet" type="text/css" href="/static/assets/css/service.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">

</head>
<body>
  {% if user.is_authenticated %}
  
        <div class="sidebar">
          <div class="logo-details">
                
            <div class="logo_name">Menu</div>
                <i class='bi bi-list' id="btn" ></i>
            </div>
            <ul class="nav-list">
             
              <li>
                  <a href="{% url 'facturation:homepage' %}">
                  <i class='bi bi-journal-text'></i>
                  <span class="links_name">Factures</span>
                  </a>
                  <span class="tooltip">Factures</span>
              </li>
              <li>
                  <a href="{% url 'facturation:fournisseurs' %}">
                  <i class='bi bi-people-fill' ></i>
                  <span class="links_name">Fournisseurs</span>
                  </a>
                  <span class="tooltip">Fournisseurs</span>
              </li>
              <li>
                  <a href="{% url 'facturation:services' %}">
                  <i class='bi bi-nut' ></i>
                  <span class="links_name">Services</span>
                  </a>
                  <span class="tooltip">Services</span>
              </li>
              <li>
                  <a href="{% url 'facturation:logout' %}">
                  <i class='bi bi-box-arrow-left' ></i>
                  <span class="links_name">Logout</span>
                  </a>
                  <span class="tooltip">logout</span>
              </li>
        
            </ul>
          </div>
        </div>

    <script>
    let sidebar = document.querySelector(".sidebar");
    let closeBtn = document.querySelector("#btn");
    let searchBtn = document.querySelector(".bx-search");
    closeBtn.addEventListener("click", ()=>{
      sidebar.classList.toggle("open");
      menuBtnChange();//calling the function(optional)
    });
    searchBtn.addEventListener("click", ()=>{ // Sidebar open when you click on the search iocn
      sidebar.classList.toggle("open");
      menuBtnChange(); //calling the function(optional)
    });
    // following are the code to change sidebar button(optional)
    function menuBtnChange() {
    if(sidebar.classList.contains("open")){
      closeBtn.classList.replace("bi bi-list", "bx-menu-alt-right");//replacing the iocns class
    }else {
      closeBtn.classList.replace("bx-menu-alt-right","bi bi-list");//replacing the iocns class
    }
    }
    function openNav() {
      document.getElementById("mySidenav").style.width = "250px";
      document.getElementById("main").style.marginLeft = "250px";
    }
    function closeNav() {
      document.getElementById("mySidenav").style.width = "0";
      document.getElementById("main").style.marginLeft = "0";
    }
    </script>
    
    <div class='allcontainer'>
      <div class="header">
        <h1>Gestion des Factures</h1>

        <div class="add-buttons">
            {% if request.user|user_in_group:'admin' %}
            <button class="modal-button" data-modal-target="#addFactureModal">Ajouter une Facture</button>
            <button class="modal-button" data-modal-target="#addFournisseurModal">Ajouter un Fournisseur</button>
            <button class="modal-button" data-modal-target="#addServiceModal">Ajouter un Service</button>
            {%endif%}
            <button class="modal-button" data-modal-target="#Imprimer">Imprimer</button>

        </div>
        <div class="modal" id="Imprimer">
          <div class="modal-content">
         
            <div class="form-container">
              <form role="form" method="POST" action="{% url 'facturation:export_data' %}?{{request.GET.urlencode}}" enctype="multipart/form-data">
                {% csrf_token %}
                  <div class="form-group">
                    <label>Choisis le format</label>
                    <select class="custom-select" name="file-format">
                      <option selected>format...</option>
                      <option>CSV</option>
                      <option>JSON</option>
                      <option>XLS (Excel)</option>
                      <option>PDF</option>
                    </select>
                  </div> <br><br><br>
                <button type="submit" class="btn btn-info btn-block">Exporter</button>
              </form>  
            </div>
          </div>
        </div>
        {% if request.user|user_in_group:'admin' %}
        <div class="modal" id="addFactureModal">
          <div class="modal-content">
              <h2>Ajouter une Facture</h2>
              <div class="form-container">
                  <!-- Add Facture Form Content -->
                  <form method="POST">
                      {% csrf_token %}
                      {{ facture_form.as_p }}
                      <input type="submit" value="Adjouter une Facture">
                  </form>
              </div>
          </div>
        </div>
        
        <!-- Add Fournisseur Modal -->
        <div class="modal" id="addFournisseurModal">
          <div class="modal-content">
              
              <h2>Ajouter un Fournisseur</h2>
              <div class='form-container'>

                  <form method="post">
                      {% csrf_token %}
                      {{ fournisseur_form.as_p }}
                      <input type="submit" value="Ajouter un Fournisseur">
                  </form>
              </div>
          </div>
        </div>
        
        <!-- Add Service Modal -->
        <div class="modal" id="addServiceModal">
          <div class="modal-content">
              <div class="form-container">
                  <!-- Add Service Form Content -->
                  <form method="post">
                      {% csrf_token %}
                      {{ service_form.as_p }}
                      <input type="submit" value="Ajouter un  Service">
                  </form>
              </div>
          </div>
        </div>
        {%endif%}
      
      </div>

      <div class="content">
      
        {% block content %}
        {% endblock %}
      </div>
    </div>    
{% else %}
  <p>Vous n'étes pas connectés</p>
  <a href="{% url 'login' %}"> se Connecter</a>
{% endif %}
<script>
  // Add the 'active' class to the clicked pagination item
  document.addEventListener("DOMContentLoaded", function () {
      const paginationItems = document.querySelectorAll(".pagination li");
      paginationItems.forEach(item => {
          item.addEventListener("click", function () {
              paginationItems.forEach(item => item.classList.remove("active"));
              this.classList.add("active");
          });
      });
  });
</script>

    <script src="/static/assets/js/modal.js"></script>
</body>
</html>
{% endif %}

facturation_project/templates/layouts/test.html
<div class="add-buttons">
    {% if request.user|user_in_group:'admin' %}
    <button class="modal-button" data-modal-target="#addFactureModal">Add New Facture</button>
    <button class="modal-button" data-modal-target="#addFournisseurModal">Add New Fournisseur</button>
    {%endif%}
    <button class="modal-button" data-modal-target="#Imprimer">Imprimer</button>

</div>