facturation_project/facturation/urls.py
# facturation:login/urls.py
from django.urls import path
from . import views

 
app_name= 'facturation'
urlpatterns = [
    #login paths
    path('register/', views.register_user, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    #homepage paths
    path('', views.homepage, name='homepage'),
    path('homepage/', views.homepage, name='homepage'),
    #sidebar paths

    path('factures',views.homepage,name='factures'),
    path('fournisseurs/',views.fournisseurs,name='fournisseurs'),
    path('services/', views.services, name='services'),
    #CRUD for Factures
    path('add_facture/', views.add_facture, name='add_facture'),
    path('facture/<int:pk>/', views.view_facture, name='view_facture'),
    path('facture/<int:pk>/update/', views.update_facture, name='update_facture'),
    path('facture/<int:pk>/delete/', views.delete_facture, name='delete_facture'),
    # CRUD for Fournisseurs
    path('fournisseur/add/', views.add_fournisseur, name='add_fournisseur'),
    path('fournisseur/<int:pk>/', views.view_fournisseur, name='view_fournisseur'),
    path('fournisseur/<int:pk>/update/', views.update_fournisseur, name='update_fournisseur'),
    path('fournisseur/<int:pk>/delete/', views.delete_fournisseur, name='delete_fournisseur'),
    # CRUD for Services
    path('service/add/', views.add_service, name='add_service'),
    path('service/<int:pk>/', views.view_service, name='view_service'),
    path('service/<int:pk>/update/', views.update_service, name='update_service'),
    path('service/<int:pk>/delete/', views.delete_service, name='delete_service'),
    #exporting_importing
    path('export/', views.export_data, name="export_data"),

]

facturation_project/facturation_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),


    path('', include('facturation.urls',namespace='facturation')),
         
]

facturation_project/facturation/models.py
# facturation/models.py
from django.db import models
from datetime import timedelta
from django import forms
from django.contrib.auth.models import User

#class LoginForm(forms.Form):
    #username = forms.CharField(max_length=150)
    #password = forms.CharField(widget=forms.PasswordInput)



class Service(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    

class Fournisseur(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Facture(models.Model):
    numero = models.CharField(max_length=20)
    fournisseur = models.ForeignKey(Fournisseur, on_delete=models.CASCADE)
    date_facture = models.DateField()
    date_depot = models.DateField()
    montant = models.DecimalField(max_digits=10, decimal_places=2)
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    
    status = models.CharField(choices=(('draft', 'Draft'), ('validated', 'Validated'), ('paid', 'Paid')), default='draft', max_length=20)
    echeance = models.DateField(blank=True, null=True)  

    def __str__(self):
        return f"{self.numero} - {self.fournisseur} - {self.montant}"

    def save(self, *args, **kwargs):
        if not self.echeance:  # Calculate échéance date only if it's not set
            self.echeance = self.date_facture + timedelta(days=90)
        super(Facture, self).save(*args, **kwargs)

facturation_project/facturation/forms.py
# facturation/forms.py
from django.forms import ModelForm
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Facture, Fournisseur, Service


    

class SignUpForm(UserCreationForm):
    
    class Meta:
        model = User
        
        fields = ['username', 'email','password1','password2']




class FournisseurForm(forms.ModelForm):
    class Meta:
        model = Fournisseur
        fields = ['name', 'email', 'phone']
    def clean_name(self):
        name = self.cleaned_data['name']
        if Fournisseur.objects.filter(name=name).exists():
            raise forms.ValidationError("Ce fournissuer existe déja.")
        return name

class ServiceForm(forms.ModelForm):
    class Meta:
        model = Service
        fields = ['name']
    def clean_name(self):
        name = self.cleaned_data['name']
        if Service.objects.filter(name=name).exists():
            raise forms.ValidationError("Ce Service existe déja")
        return name

class FactureForm(forms.ModelForm):
    class Meta:
        model = Facture
        fields = ['numero', 'fournisseur', 'date_facture', 'date_depot', 'service', 'status','montant']
    def clean_name(self):
        numero = self.cleaned_data['numero']
        if Facture.objects.filter(numero=numero).exists():
            raise forms.ValidationError("Elle existe une facture avec le meme numero")
        return numero

class SearchView(forms.Form):
    q = forms.CharField(label="Search", max_length=200)
class SearchForm(forms.Form):
    fournisseur = forms.ModelChoiceField(queryset=Fournisseur.objects.all(), empty_label="Select Fournisseur", required=False)
    service = forms.ModelChoiceField(queryset=Service.objects.all(), empty_label="Select Service", required=False)
    date = forms.DateField(required=False, widget=forms.DateInput(attrs={'type': 'date'}))

facturation_project/facturation/views.py
# facturation/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from .forms import *
from django.contrib import messages
from .models import Facture
from .forms import FactureForm
from .decorators import *
from django.core.paginator import Paginator
#the login views
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.models import Group
from .forms import SignUpForm
from .filters import *
from .resources import FactureResource  # Import the resource
from django.template.loader import get_template
from io import BytesIO
from reportlab.lib.pagesizes import letter, landscape
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle

from django.template.loader import render_to_string
import os


from django.db.models import Q
# ...

@user_passes_test(lambda user: not user.is_authenticated, login_url='facturation:homepage')
def register_user(request):
    msg = None
    
    
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            user=form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            group=Group.objects.get(name='viewer')

            #user = authenticate(username=username, password=password)
            user.groups.add(group)
            login(request, user)

            return redirect("facturation:homepage")

        else:
            msg = 'Form is not valid'
    else:
        form = SignUpForm()
    return render(request, "templates/facturation/register.html", {"form": form, "msg": msg})
@unauthenticated_user
def login_view(request):
    
        
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        
        if user is not None:
            login(request, user)
            if request.GET.get('next', None):
                return HttpResponseRedirect(request.GET['next'])
            else:
                return redirect("facturation:homepage")
        else:
            form = AuthenticationForm()
            return render(request, 'facturation/login.html', {'form': form})
     
    else:
        form = AuthenticationForm()
        return render(request, 'facturation/login.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('facturation:login')






#the homepage view
@login_required(login_url='facturation:login')
def homepage(request):

    if request.method == 'POST':
        facture_form = FactureForm(request.POST)
        fournisseur_form = FournisseurForm(request.POST)
        service_form = ServiceForm(request.POST)
    

        if facture_form.is_valid():
            facture_form.save()
            return redirect('facturation:homepage')
        if fournisseur_form.is_valid():
            fournisseur_form.save()
            return redirect('facturation:homepage')
        if service_form.is_valid():
            service_form.save()
            return redirect('facturation:homepage')

    else:
        facture_form = FactureForm()
        fournisseur_form = FournisseurForm()
        service_form = ServiceForm()
    factures = Facture.objects.all()  # This is for the homepage view
    search_query = request.GET.get('q')
    factures = Facture.objects.order_by('-date_depot')

    myFilter= FactureFilter(request.GET ,queryset=factures) # This is for the homepage view
    factures_filtered=myFilter.qs
    request.session['filter_params'] = request.GET.dict()
    if search_query:
        factures_filtered = factures_filtered.filter(
            Q(numero__icontains=search_query) |
            Q(fournisseur__name__icontains=search_query) |
            Q(date_depot__icontains=search_query)|
            Q(montant__icontains=search_query)

            )
    paginator = Paginator(factures_filtered, 6)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)



    return render(request, 'facturation/homepage.html', { 'factures_filtered': page,
        'facture_form': facture_form,
        'fournisseur_form': fournisseur_form,
        'service_form': service_form,
        'myFilter':myFilter,  # This ensures the filter form is also present on the page
        'page':page,
    })



#the sidebar view 




@login_required(login_url='facturation:login')
def services(request):
    if request.method == 'POST':
        facture_form = FactureForm(request.POST)
        fournisseur_form = FournisseurForm(request.POST)
        service_form = ServiceForm(request.POST)

        if facture_form.is_valid():
            facture_form.save()
            return redirect('facturation:homepage')
        if fournisseur_form.is_valid():
            fournisseur_form.save()
            return redirect('facturation:homepage')
        if service_form.is_valid():
            service_form.save()
            return redirect('facturation:homepage')

    else:
        facture_form = FactureForm()
        fournisseur_form = FournisseurForm()
        service_form = ServiceForm()
    services = Service.objects.all()

    return render(request, 'facturation/service.html', {'services': services,'facture_form': facture_form,
        'fournisseur_form': fournisseur_form,
        'service_form': service_form,
    })


@login_required(login_url='facturation:login')
def fournisseurs(request): 
    if request.method == 'POST':
        facture_form = FactureForm(request.POST)
        fournisseur_form = FournisseurForm(request.POST)
        service_form = ServiceForm(request.POST)

        if facture_form.is_valid():
            facture_form.save()
            return redirect('facturation:homepage')
        if fournisseur_form.is_valid():
            fournisseur_form.save()
            return redirect('facturation:homepage')
        if service_form.is_valid():
            service_form.save()
            return redirect('facturation:homepage')

    else:
        facture_form = FactureForm()
        fournisseur_form = FournisseurForm()
        service_form = ServiceForm()
    Fournisseurs=Fournisseur.objects.all()
    myFilter= FournisseurFilter(request.GET ,queryset=Fournisseurs) # This is for the homepage view
    Fournisseurs=myFilter.qs
    paginator=Paginator(Fournisseurs,10)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)

    return render(request, 'facturation/fournisseurs.html',{'Fournisseurs':page,'facture_form': facture_form,
        'fournisseur_form': fournisseur_form,
        'service_form': service_form,
        'myFilter':myFilter,
        'page':page
        })



#the header view 
@login_required(login_url='facturation:login')
@allowed_users(allowed_roles=['admin'])
def add_facture(request):
    if request.method == 'POST':
        form = FactureForm(request.POST)
        if form.is_valid():
            facture_numero=form.cleaned_data['numero']
            if Facture.objects.filter(numero=facture_numero).exists():
                messages.error(request, f"Une facture avec le meme numero : '{facture_numero}' existe deja.")
            else:
                form.save()
                return redirect('facturation:homepage')
    else:
        form = FactureForm()
    return render(request, 'facturation/add_facture.html', {'form': form})

@login_required(login_url='facturation:login')
@allowed_users(allowed_roles=['admin'])
def add_fournisseur(request):
    if request.method == 'POST':
        form = FournisseurForm(request.POST)
        if form.is_valid():
            fournisseur_name = form.cleaned_data['name']
            if Fournisseur.objects.filter(name=fournisseur_name).exists():
                # Supplier with this name already exists, show an error message
                messages.error(request, f" le Fournisseur '{fournisseur_name}' existe deja")
            else:
                form.save()
                return redirect('facturation:homepage')
    else:
        form = FournisseurForm()
    return render(request, 'facturation/add_fournisseur.html', {'form': form})

@login_required(login_url='facturation:login')
@allowed_users(allowed_roles=['admin'])
def add_service(request):
    if request.method == 'POST':
        form = ServiceForm(request.POST)
        if form.is_valid():
            service_name = form.cleaned_data['name']
            if Service.objects.filter(name=service_name).exists():
                # Supplier with this name already exists, show an error message
                messages.error(request, f"Service '{service_name}' already exists.")
            else:
                form.save()
                return redirect('facturation:homepage')
    else:
        form = ServiceForm()
    return render(request, 'facturation/add_service.html', {'form': form})

@login_required(login_url='facturation:login')
@allowed_users(allowed_roles=['admin'])
def search(request):
     
        form = SearchForm(request.GET)
        factures = Facture.objects.all()

        if form.is_valid():
            fournisseur = form.cleaned_data['fournisseur']
            service = form.cleaned_data['service']
            date = form.cleaned_data['date']

            if fournisseur:
                factures = factures.filter(fournisseur=fournisseur)
            if service:
                factures = factures.filter(service=service)

facturation_project/templates/facturation/add_fournisseur.html
<!-- templates/invoices/add_fournisseur.html -->
<!DOCTYPE html>
<html>
<head>
    <title>Add Fournisseur</title>
</head>
<body>
    <h1>Add Fournisseur</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Add Fournisseur">
    </form>
</body>
</html>

facturation_project/templates/facturation/delete_facture.html
{% extends "layouts/base.html" %}
{% block content %}
<div class='modal show'>
    <div class='blok'>
        <h1>Supprimer la  Facture</h1>
        <p>Etes vous sur de supprimer la facture numéro: {{ facture.numero }}?</p>
        <form method="POST">
            {% csrf_token %}
            <input type="submit" value="Supprimer">
        </form>
        <a href="{% url 'facturation:homepage' %}">Annuler</a>
    </div>
</div>
{%endblock%}

facturation_project/templates/facturation/export_data.html
<div class="impression">
  
    <form role="form" method="POST" action="{% url 'facturation:export_data' %}?{{request.GET.urlencode}}" enctype="multipart/form-data">
      {% csrf_token %}
        <div class="form-group">
          <label>Choose Format Type</label>
          <select class="custom-select" name="file-format">
            <option selected>Choose format...</option>
            <option>CSV</option>
            <option>JSON</option>
            <option>XLS (Excel)</option>
            <option>PDF</option>
          </select>
        </div> <br><br><br>
      <button type="submit" class="btn btn-info btn-block">Export</button>
    </form>
  
</div>

facturation_project/templates/facturation/export_data_pdf.html
<!DOCTYPE html>
<html>
<head>
    <title>Exported Data</title>
    
   
    
    
    <style>
        body {
            font-family: Arial, sans-serif;
            
            margin: 0;
            padding: 0;
            min-height: 100vh;
        }

        .table-container {
            margin: 20px 30px; /* Adjust margins as needed */
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        th, td {
            border: 1px solid #e0e0e0;
            padding: 10px;
        }

        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2;
        }
    </style>

   
</head>
<body>
    
        <table>
            
            <tr>
                <th>N°Facture</th>
                <th>Fournisseur</th>
                <th>Date Facture</th>
                <th>Date Dépot</th>
                <th>Date Échéance</th>
                <th>Service</th>
                <th>Montant</th>
                <th>Status</th>
                
                <!-- Add other headers here -->
            </tr>
            
            <tbody>
                {% for row in data %}
                    <tr>
                        <td>{{ row.numero }}</td>
                        <td>{{ row.fournisseur }}</td>
                        <td>{{ row.date_facture }}</td>
                        <td>{{ row.date_depot }}</td>
                        <td>{{ row.echeance }}</td>
                        <td>{{ row.service }}</td>
                        <td>{{ row.montant }}</td>
                        <td>{{ row.status }}</td>
                        <!-- Add other data fields here -->
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    
</body>
</html>

facturation_project/templates/facturation/factures.html
{% extends "layouts/base.html" %}

{% block content %}
<div class='home-section'>
    <table>
        <tr>
            <th>N°Facture</th>
            <th>Fournisseur</th>
            <th>Date Facture</th>
            <th>Date Dépot</th>
            <th>Date Échéance</th>
            <th>Service</th>
            <th>Montant</th>
            <th>Status</th>
            <th>Action</th>
        </tr>
        {% for facture in factures %}
        <tr>
            <td>{{ facture.number }}</td>
            <td>{{ facture.fournisseur }}</td>
            <td>{{ facture.date_facture }}</td>
            <td>{{ facture.date_depot }}</td>
            <td>{{ facture.date_echeance }}</td>
            <td>{{ facture.service }}</td>
            <td>{{ facture.montant }}</td>
            <td>{{ facture.status }}</td>
            <td>
                <a href="{% url 'facturation:view_facture' facture.pk %}">View</a>
                <a href="{% url 'facturation:update_facture' facture.pk %}">Update</a>
                <a href="{% url 'facturation:delete_facture' facture.pk %}">Delete</a>
            </td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

facturation_project/templates/facturation/homepage.html
{% extends "layouts/base.html" %}
{% load group_tags %}


{% block content %}
<div class='home-section'>
    <div class="search-and-filters">
        
        <div class="filters">
            <form method="GET">
                {{ myFilter.form }}
                <button type="submit">Filtrer</button>
            </form>
        </div>
        <div class="search-bar">
            <form method="GET" action="{% url 'facturation:homepage' %}">
               
                <input type="text" id="search-input" value="{{request.GET.q}}" name="q" placeholder="Rechercher...",name='search'>
                <button id="search-button">Rechercher</button>
            </form>
        </div>
    </div>
    <table>
        <tr>
            <th>N°Facture</th>
            <th>Fournisseur</th>
            <th>Date Facture</th>
            <th>Date Dépot</th>
            <th>Date Échéance</th>
            <th>Service</th>
            <th>Montant</th>
            <th>Status</th>
            <th>Action</th>
        </tr>
        <tbody id="table-body">
        {% for facture in factures_filtered %}
        <tr>
            <td>{{ facture.numero }}</td>
            <td>{{ facture.fournisseur }}</td>
            <td>{{ facture.date_facture }}</td>
            <td>{{ facture.date_depot }}</td>
            <td>{{ facture.echeance }}</td>
            <td>{{ facture.service }}</td>
            <td>{{ facture.montant }}</td>
            <td>{{ facture.status }}</td>
            <td>
                <a href="{% url 'facturation:view_facture' facture.pk %}">
                    <i class="bi bi-eye-fill"></i>
                </a><br/>
                {% if request.user|user_in_group:'admin' %}
                <a href="{% url 'facturation:update_facture' facture.pk %}">
                    <i class="bi bi-pencil-fill"></i>
                </a><br/>
                <a href="{% url 'facturation:delete_facture' facture.pk %}">
                    <i class="bi bi-trash3-fill"></i>
                </a>
                {%endif%}
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    
    <div class="pagination">
        {% if factures_filtered.has_previous %}
            <a href="?page={{ factures_filtered.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">&laquo;</a>
        {% else %}
            <span class="disabled">&laquo;</span>
        {% endif %}
    
        {% for i in factures_filtered.paginator.page_range %}
            {% if factures_filtered.number == i %}
                <span class="current">{{ i }}</span>
            {% else %}
                <a href="?page={{ i }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ i }}</a>
            {% endif %}
        {% endfor %}
    
        {% if factures_filtered.has_next %}
            <a href="?page={{ factures_filtered.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">&raquo;</a>
        {% else %}
            <span class="disabled">&raquo;</span>
        {% endif %}
    </div>
    
    

</div>


<!-- Votre code JavaScript ici -->

{% endblock %}

facturation_project/templates/facturation/login.html
<!-- templates/registration/login.html -->
{% extends 'layouts/base-fullscreen.html' %}
{% block title %} Login {% endblock title %}

{% block content %}

           
                    <h2 class="text-center mb-4">Se connecter</h2>
                    {% if messages %}
                        <div class="alert alert-danger">
                            {% for message in messages %}
                                {{ message }}
                            {% endfor %}
                        </div>
                    {% endif %}
                    
                    <form method="POST">
                        {% csrf_token %}
                        
                        <div class="form-group">
                            <input type="text" name="username" placeholder="Username" class="form-control">
                            <span class="text-error">{{ form.username.errors }}</span>
                        </div>
                        
                        <div class="form-group">
                            <input type="password" name="password" placeholder="Password" class="form-control">
                            <span class="text-error">{{ form.password.errors }}</span>
                        </div>
                        
                        <div class="custom-control custom-checkbox">
                            <input class="custom-control-input" id="customCheckLogin" type="checkbox">
                            <label class="custom-control-label" for="customCheckLogin">
                                <span class="text-muted">Remember me</span>
                            </label>
                        </div>
                        
                        <div class="text-center mt-4">
                            <button type="submit" class="btn btn-primary">Connecter</button>
                        </div>
                    </form>
                    
                    <p class="mt-3 text-center">Don't have an account? <a href="{% url 'facturation:register' %}">Register here</a>.</p>
            
{% endblock %}

facturation_project/templates/facturation/popup_delete.html
<!-- Display a confirmation message and delete button -->
<p>Are you sure you want to delete {{ fournisseur.name }}?</p>
<form method="post" action="{% url 'facturation:delete_fournisseur' fournisseur.pk %}">
    {% csrf_token %}
    <button type="submit">Delete</button>
</form>

facturation_project/templates/facturation/popup_update.html
<!-- Add the form for updating the fournisseur -->
<form method="post" action="{% url 'facturation:update_fournisseur' fournisseur.pk %}">
    {% csrf_token %}
    <!-- Add form fields here -->
    <button type="submit">Update</button>
</form>

facturation_project/templates/facturation/service.html
{% extends "layouts/base.html" %}
{% load group_tags %}

{% block content %}
<div class='home-section'>
    <h2>Services</h2>
    <table>
        <tr>
            <th>Nom de service</th>
            {% if request.user|user_in_group:'admin' %}      
            <th>Actions</th>
            {%endif%}
        </tr>
        {% for service in services %}
        <tr>
            <td>{{ service.name }}</td>
            {% if request.user|user_in_group:'admin' %}  
            <td>
                              
                <a href="{% url 'facturation:update_service' service.pk %}">Modifier</a>
                <a href="{% url 'facturation:delete_service' service.pk %}">Supprimer</a>
              
            </td>
            {%endif%}
        </tr>
        {% endfor %}
    </table>
   
</div>
{% endblock %}

facturation_project/templates/facturation/update_facture.html
{% extends "layouts/base.html" %}

{% block content %}
<div class='modal show'>
    <div class='blok'>
        <h1 >Modifier la Facture</h1>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Modifier">
        </form>
        <a href="{% url 'facturation:view_facture' facture.pk %}">Annuler</a>
    </div>
</div>
{%endblock%}

facturation_project/templates/facturation/update_fournisseur.html
{% extends "layouts/base.html" %}

{% block content %}
<div class='modal show'>
    <div class ='blok'>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Save Changes</button>
        </form>
    </div>
</div>
{% endblock %}

facturation_project/templates/facturation/update_service.html
{% extends "layouts/base.html" %}

{% block content %}
<div class='modal show'>
    <div class='blok'>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Enregistrer</button>
        </form>
    </div>
</div>
{% endblock %}

facturation_project/templates/facturation/view_fournisseur.html
{% extends "layouts/base.html" %}

{% block content %}
<h2>{{ fournisseur.nom }}</h2>
<p>Email: {{ fournisseur.email }}</p>
<p>Phone: {{ fournisseur.phone }}</p>
<a href="{% url 'facturation:update_fournisseur' fournisseur.pk %}">Edit</a>
<a href="{% url 'facturation:delete_fournisseur' fournisseur.pk %}">Delete</a>
{% endblock %}